config/routes.rb
Whereto::Application.routes.draw do

  root :to => 'pages#home'
  
  resources :venues, :only => [:index, :show]
  
  match '/history', :to => 'pages#history'
  match '/home', :to => 'pages#home'
  match '/search', :to => 'pages#search'
  match '/tags', :to => 'pages#tags'
  match '/dbcounts', :to => 'pages#dbcounts'

end

app/models/patron.rb
class Patron < ActiveRecord::Base
	has_many :venues, :through => :visits
	
	validates :foursquare_id, 		:presence => true,
									:uniqueness => { :case_sensitive => false }
									
	def to_param
    foursquare_id
  end
									
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/venue.rb
class Venue < ActiveRecord::Base
	has_many :patrons, :through => :visits
	
	validates :foursquare_id, 		:presence => true,
									:uniqueness => { :case_sensitive => false }
	
	validates :name, 				:presence => true
	
  default_scope :order => 'name ASC'
  
  def to_param
    foursquare_id
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
	belongs_to :venue
	belongs_to :patron
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
end

app/controllers/pages_controller.rb
require 'rubygems'
require 'net/https'

class PagesController < ApplicationController
  
  def home
    @title = "Home"
    
    # oauth_key = 'HD5ZYV1DJSQE2FXEX32F54205X43WQ3W2LTEVORFD413OCAL'
    # oauth_secret = '1JGVNUDPLFNTDMLYA0I4DMW0ERPVYAFUMJAULLUJVCKHLBKP'

    oauth_key = 'client_id'
    oauth_secret = 'client_secret'

  end
  
  def history
	  @title = "History"
	  @all_visits_count = Visit.all.count
  end
  
  def tags
    @tags = Tag.all
  end
  
  def search
    @title = "Find a Venue"
  end
  
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
  end

  def show
    @venue = Venue.find_by_foursquare_id(params[:id])
    if @venue.nil?
      @title = "Venue Not Found"
    else
      @title = @venue.name
    end
  end
end

app/controllers/visits_controller.rb
require 'rubygems'
require 'net/https'

class PagesController < ApplicationController
  
  def home
    @title = "Home"
    
    # oauth_key = 'HD5ZYV1DJSQE2FXEX32F54205X43WQ3W2LTEVORFD413OCAL'
    # oauth_secret = '1JGVNUDPLFNTDMLYA0I4DMW0ERPVYAFUMJAULLUJVCKHLBKP'

    oauth_key = 'client_id'
    oauth_secret = 'client_secret'
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title
      base_title = "WhereTo"
      if @title.nil?
          base_title
      else
        "#{base_title} | #{@title}"
      end
  end
  
  
end

app/helpers/pages_helper.rb
require 'net/https'

module PagesHelper
	
	def get_all_checkins_on(year, month, day) #format should be YYYY-MM-DD
		target_day = Time.local(year, month, day, '12:00:00')
		day_start = target_day.to_i
		day_end = day_start + 86400		
		@visits = Visit.where(:fs_created_at => day_start..day_end).all
	end
	
	def predict_checkins(time)
	  t = time
	  tminus2hours = time - 2.hours
		@visits = Visit.where(:fs_created_at => day_start..day_end).all	  
  end
	
	
	def perform_graph_request(endpoint, params = {}, method = "get")
		@access_token = '2MBSVSBZNE5LHAA4RKQNXZI1Q30BXD1PR12ALR12KQTPLBF1'
		@base_url = "https://api.foursquare.com/v2/"

		@query_string = "?"
		@query_string += "oauth_token=#{CGI.escape(@access_token)}"
	
		if method=="get"
			params.each{|key, val| @query_string += "&#{key}=#{val}"}
			url = URI.parse("#{@base_url}#{endpoint}#{@query_string}")
			request = Net::HTTP::Get.new("#{url.path}?#{url.query}",{"Content-Type"=>"text/json"})
		else
			url = URI.parse("#{@base_url}#{endpoint}#{@query_string}")
			request = Net::HTTP::Post.new("#{url.path}?#{url.query}",{"Content-Type"=>"text/json"})
			request.set_form_data(params)
		end
		
		
		http = Net::HTTP.new(url.host, url.port)
		http.use_ssl = true
		response = JSON.parse(http.start {|http| http.request(request) }.body)
		response
    end
	
	def herenow(venue_id)
      perform_graph_request("venues/#{venue_id}/herenow", {})
  end
	
	def search(params={})
      params = {:ll => "37.792694,-122.409325",
                :llAcc => "100",
                :alt => "0",
                :altAcc=>"100",
                :query=>"",
                :limit=>"50",
                :intent=>"checkin"}.merge!(params)

      perform_graph_request("venues/search", params)
    end
	
	def trending(params={})
		params = {:ll => "40.723291,-73.991815",
				      :radius => "2000",
              :limit=>"50"}.merge!(params)

		perform_graph_request("venues/trending", params)
  end
  
	def get_venue(venue_id)
      perform_graph_request("venues/#{venue_id}", {})
  end
	
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<ul>
		<li><%= link_to root_path do |l| %><span class="icon">⌂</span><% end %></li>
		<li><span class="icon">l</span></li>
		<li><span class="icon">f</span></li>
		<li><span class="icon">❤</span></li>
		<li><%= link_to search_path do |l| %><span class="icon">z</span><% end %></li>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<header>
	<h4>Where To?</h4>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag "custom" %>
  <%= stylesheet_link_tag "venues" %>
  <%= stylesheet_link_tag "ficostyle" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "RGraph.bar" %>
  <%= javascript_include_tag "RGraph.bipolar" %>
  <%= javascript_include_tag "RGraph.common.adjusting" %>
  <%= javascript_include_tag "RGraph.common.annotate" %>
  <%= javascript_include_tag "RGraph.common.context" %>
  <%= javascript_include_tag "RGraph.common.core" %>
  <%= javascript_include_tag "RGraph.common.effects" %>
  <%= javascript_include_tag "RGraph.common.key" %>
  <%= javascript_include_tag "RGraph.common.resizing" %>
  <%= javascript_include_tag "RGraph.common.tooltips" %>
  <%= javascript_include_tag "RGraph.common.zoom" %>
  <%= javascript_include_tag "RGraph.fuel" %>
  <%= javascript_include_tag "RGraph.funnel" %>
  <%= javascript_include_tag "RGraph.gantt" %>
  <%= javascript_include_tag "RGraph.gauge" %>
  <%= javascript_include_tag "RGraph.hbar" %>
  <%= javascript_include_tag "RGraph.hprogress" %>
  <%= javascript_include_tag "RGraph.line" %>
  <%= javascript_include_tag "RGraph.meter" %>
  <%= javascript_include_tag "RGraph.modaldialog" %>
  <%= javascript_include_tag "RGraph.odo" %>
  <%= javascript_include_tag "RGraph.pie" %>
  <%= javascript_include_tag "RGraph.radar" %>
  <%= javascript_include_tag "RGraph.rose" %>
  <%= javascript_include_tag "RGraph.rscatter" %>
  <%= javascript_include_tag "RGraph.scatter" %>
  <%= javascript_include_tag "RGraph.skeleton" %>
  <%= javascript_include_tag "RGraph.thermometer" %>
  <%= javascript_include_tag "RGraph.vprogress" %>
  <%= javascript_include_tag "RGraph.waterfall" %>
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="viewport"  content="width=device-width,  minimum-scale=1.0, maximum-scale=1.0" />
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
</head>
<body>
	<div class="iphone_wrapper">
		<%= render 'layouts/header' %>
		<%= render 'layouts/footer' %>		
		<div class="content_wrapper">
			<%= yield %>
		</div>
	</div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/dbcounts.html.erb
<h1>Database Counts</h1>
Venues: <%= Venue.count %></br>
Patrons: <%= Patron.count %></br>
Checkins: <%= Visit.count %>

app/views/pages/history.html.erb
<h2>Today's Checkins So Far.</h2>

<% 
	t = Time.now
	cur_year = t.year
	cur_month = t.month
	cur_day = t.day
	today_checkins = get_all_checkins_on(cur_year, cur_month, cur_day)
%>

<div class="today">Today's Checkins: <%= today_checkins.count %></div>
<div class="all_time">Total Checkins: <%= @all_visits_count %>

app/views/pages/home.html.erb
<script type="text/javascript">
var lat = 40.718493; //Global variables for lat/long by default in the E.Village/LES area
var long = -73.993177;
var current_time = new Date();
var epochtime = current_time.getTime();
var categories = ["Bar","Sports Bar","Dive Bar","Pub","Restaurant","Nightclub"];
var cur_patron = 0;	
$(document).ready(function(){
	navigator.geolocation.getCurrentPosition(foundLocation, noLocation);
	function foundLocation(position){
	  	lat = position.coords.latitude;
	  	long = position.coords.longitude;
		printVenues();
	}
	function noLocation(){
	  alert('Could not find location');
	}
	//Clear the list in the center
	$('ul.venue_list').html("");
	venue_rank = 0;
	
	function printVenues(){
		$.ajax({
			url: 'https://api.foursquare.com/v2/venues/trending?ll='+lat+','+long+'&oauth_token=2MBSVSBZNE5LHAA4RKQNXZI1Q30BXD1PR12ALR12KQTPLBF1',
			dataType: 'json',
			async: false,
			success: 	function(venue_data){
							var venue_list = venue_data['response']['venues'];
							$.each(venue_list, 	function(k){
								var patron_list = [];

								//First need to narrow down according to the categories array.
								//Do that later
								var good_category = 0;
								var venue_categories = venue_list[k]['categories'];
								$.each(venue_categories, function(z){
									
									if(good_category==1){
										return false;
									}
									$.each(categories, function(y){
										if(good_category==1){
											return false;
										}
										if(venue_categories[z]['name']==categories[y]){
											good_category = 1;
											return false;
										}
									});
								});

						      	if(good_category==1){
									venue_rank = venue_rank + 1;							
									//Second need to collect all the patrons and calculate ratios, survivors, etc.
									var girl_count_w = 0;
									var guy_count_w = 0;
									var girl_count = 0;
									var guy_count = 0;
									$.ajax({
										url: 'https://api.foursquare.com/v2/venues/'+venue_list[k]['id']+'/herenow?oauth_token=2MBSVSBZNE5LHAA4RKQNXZI1Q30BXD1PR12ALR12KQTPLBF1',
										dataType: 'json',
										async: false,
										success: 	function(patron_data){
											patron_list = patron_data['response']['hereNow']['items'];
											$.each(patron_list, function(l){
												m = ((epochtime - patron_list[l]['createdAt'])/60);
												if(patron_list[l]['user']['gender'] == 'female'){
													girl_count = girl_count + 1;
												}
												else{
													guy_count = guy_count + 1;
												}
											});
										}
									});
									//Need to append the venue information to the trending_list_dive
									var venue_address = venue_list[k]["location"]["address"].replace(' ','%20');
									var venue_html = '<li id="'+venue_list[k]['id']+'top" class="venue"><span class="rank">'+venue_rank+'</span>';
									venue_html = venue_html + '<span class="venue_name"><a href="<%= venues_path %>/'+ venue_list[k]["id"] +'">';
									venue_html = venue_html + venue_list[k]['name'];
									venue_html = venue_html + '</a></span><br/><span class="venue_stats"><span class="icon people_icon">u</span>';
									venue_html = venue_html + (girl_count + guy_count);
									venue_html = venue_html	+ ' | <span class="icon graph_icon">C</span>'+ Math.round((girl_count*100/(girl_count+guy_count))*100)/100 +'%</span>';
									venue_html = venue_html + '<span id="map_link"><a href="http://maps.google.com/maps?q='+ venue_list[k]["name"] + ' ' + venue_list[k]["location"]["address"] + ' new york ny" target="_blank"><span class="icon view-button">⬇</span></a></span>';
									venue_html = venue_html + '<span id="'+ venue_list[k]["id"] + '" class="icon view-button">E</span></li>';
									
									var patron_html = '<div class="'+ venue_list[k]["id"] + ' girl_list hidden">';
									patron_html = patron_html + '<ul class="patron_list" id="list' + venue_list[k]["id"] + '">';
							
									var patron_count = 0;
									$.each(patron_list, function(l){
										if(patron_list[l]['user']['gender'] == 'female'){
											if(patron_count == 0){
												patron_html = patron_html + '<li class="patron" id="patron_0">';
												patron_count = patron_count + 1
											}
											else{
												patron_html = patron_html + '<li class="patron hidden" id="patron_'+ patron_count + '">';
												patron_count = patron_count + 1;
											}
											patron_html = patron_html + '<span id="' + venue_list[k]['id'] + '" class="icon left_arrow">←</span>';
											patron_html = patron_html + '<img src="' + patron_list[l]['user']['photo'] + '" width="40">';
											patron_html = patron_html + '<div class="patron_data">';
											patron_html = patron_html + '<span class="name">' + patron_list[l]['user']['firstName'] + ' ' + patron_list[l]['user']['lastName'] + '</span>';
											patron_html = patron_html + '<br/>Checked in ' + Math.round(((epochtime/(1000) - patron_list[l]['createdAt'])/60)) + ' minutes ago';
											patron_html = patron_html + '</div>';
											patron_html = patron_html + '<span id="'+ venue_list[k]['id'] + '" class="icon right_arrow">→</span>';
											patron_html = patron_html + '</li>';
										}
									});
							
								
									patron_html = patron_html + '</ul></div>';



									var button_to_find = 'li#'+venue_list[k]["id"]+'top span.view-button';
									$('ul.venue_list').append(venue_html).find(button_to_find).bind('click', function(){
										var divid = "div." + $(this).attr("id");
										$(divid).siblings().addClass("hidden");
										$(divid).slideToggle("slow");
										cur_patron = 0;
									}); //Close of append and bind.
									
									var arrow_to_find = 'span#'+venue_list[k]["id"];
									$('ul.venue_list').append(patron_html).find(arrow_to_find).bind('click', function(){
										var direction_text = $(this).attr("class");
										var direction_array = direction_text.split(' ');
										var direction = direction_array[1];
										
										if(direction=='right_arrow'){
											var venid = $(this).attr("id");
											var cur_list = "ul#" + venid;
											if($(this).parent().index()==$(this).parent().siblings().length-1){
											}
											else{
												$(this).parent().addClass("hidden");
												$(this).parent().next().removeClass("hidden");
											}
										}
										
										if(direction=='left_arrow'){
											var venid = $(this).attr("id");
											var cur_list = "ul#" + venid;
											if($(this).parent().index()==0){
											}
											else{
												$(this).parent().addClass("hidden");
												$(this).parent().prev().removeClass("hidden");
											}
										}
									});
								} //Close of if good category == 1
						
							});
						}
		});
	}

});

</script>

<div class="trending_list">
	<ul class="venue_list">
	</ul>
</div>

<script type="text/javascript">
$(document).ready(function(){
	var cur_patron = 0;	
	$("span.view-button").click(function(){
		var divid = "div." + $(this).attr("id");
		$(divid).siblings().addClass("hidden");
		$(divid).slideToggle("slow");
		cur_patron = 0;
	});

	$("span.left_arrow").click(function(){
		var venid = $(this).attr("id");
		var cur_list = "ul#" + venid;
		if($(this).parent().index()==0){
		}
		else{
			$(this).parent().addClass("hidden");
			$(this).parent().prev().removeClass("hidden");
		}
	});

	$("span.right_arrow").click(function(){
		var venid = $(this).attr("id");
		var cur_list = "ul#" + venid;
		if($(this).parent().index()==$(this).parent().siblings().length-1){
		}
		else{
			$(this).parent().addClass("hidden");
			$(this).parent().next().removeClass("hidden");
		}
	});
});
</script>

app/views/pages/search.html.erb
<div class="search_page">
	<% if @results.nil? %>
		<input id="search_field" type="text" class="venue_search" placeholder="Enter a Venue's Name"/><div id="venue_submit" class="venue_search_submit" >Search</div>
	<% else %>
		
	<% end %>
</div>

app/views/venues/show.html.erb
<div class="venue_page">
<% if @venue.nil? %>
<h1>Venue Not Found</h1>
<% else %>
<h1><%= @venue.name %></h1>
<% end %>

<div class="venue_type_canvas">
	<canvas id="venue_radar_graph" width="320" height="320" style="display:inline-block;"></canvas>
</div>

</div>

<% unless @venue.nil? %>
<script type="text/javascript">

	//Load the cycle data into the graph
	var graph_data = [<%= @venue.frat_score %>, <%= @venue.sport_score %>, <%= @venue.hipster_score %>, <%= @venue.dive_score %>, <%= @venue.exclusive_score %>, <%= @venue.dance_score %>];
	//Change the labels so they fit:
	var ymax = <%= [@venue.frat_score, @venue.sport_score, @venue.hipster_score, @venue.dive_score, @venue.exclusive_score, @venue.dance_score].max %>;
	var labels = ['Fratty', 'Sporty', 'Hipster', 'Divey', 'Exclusive', 'Dance'];
	var tooltips = ["SAE, AEPi, KA, IDK...whatever that was <br/>back in the day. We were a bit <br/>too wasted then, and we're<br/> a bit too wasted now.","Fuck Tech, go State! <br/>Screw tailgating, we're kegstanding.<br/> Wings, beer, pizza, and a 30 inch LCD<br/>...that's how we do!", "Le Sigh...Corporations Suck. <br/>Fuck the man. That place used <br/>to be cool. Now everyone goes there.<br/> Shaving is sooo passe.", "Yep, I'm broke. PBR a 3-legged<br/> table, and an angry bartender<br/> are good enough at this point.<br/> I'm gonna need to put my place <br/>on Airbnb soon.", "Did you hear? The <br/>Ex-President-of-France-Paris-Hilton<br/>-Kim-Kardashian-Justin-Beiber-<br/>Bottle-Service-Inventing-Oil-Heiress<br/> was totally here last night. <br/>XoXo.", "Thump. Thump. Thump. Thump.<br/> Fist-Pump. Pump. Pump. Pump.<br/> Techno-Electronica-Dubstepping Adventures. <br/>WHAT?" ]
	
	//Instantiate the new graph
	var venue_radar_chart = new RGraph.Rose('venue_radar_graph', graph_data);
	venue_radar_chart.Set('chart.colors.alpha', 0.9);
	venue_radar_chart.Set('chart.labels', labels);
	venue_radar_chart.Set('chart.ymax', ymax);
	venue_radar_chart.Set('chart.text.size', 8);
	venue_radar_chart.Set('chart.gutter.left', 60);
	venue_radar_chart.Set('chart.gutter.right', 60);		
	venue_radar_chart.Set('chart.colors', ['#111111']);
	venue_radar_chart.Set('chart.tooltips', tooltips);
	venue_radar_chart.Set('chart.tooltips.effect', 'expand');

	
	//Render the graph
	RGraph.Effects.Fade.In(venue_radar_chart);
</script>
<% end %>